name: Visualize Repo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  visualize-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "images/diagram.svg"  # Speicherort des Diagramms
          excluded_paths: ""  # Ordner, die ausgeschlossen werden
          should_push: true  # Diagramm wird als Commit gepusht
